export const AUTOCOMPLETE_EDITING_BOOK_BY_ISBN = 'AUTOCOMPLETE_EDITING_BOOK_BY_ISBN';

export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_BOOK_DETAILS = 'FETCH_BOOK_DETAILS';

export const REGISTER_EDITING_BOOK = 'REGISTER_EDITING_BOOK';

export const FETCH_MIMES = 'FETCH_MIMES';

export const UPDATE_BOOK = 'UPDATE_BOOK';
export const DELETE_EDITING_BOOK = 'DELETE_EDITING_BOOK';
export const DELETE_FILE = 'DELETE_FILE';

export const OPEN_DIALOG = 'OPEN_DIALOG';
