export const SET_ALERT_MESSAGE = 'SET_ALERT_MESSAGE';
export const DELETE_ALERT_MESSAGE = 'DELETE_ALERT_MESSAGE';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const SET_DIALOG_TYPE = 'SET_DIALOG_TYPE';
export const SET_OVERLAY = 'SET_OVERLAY';

export const SET_EDITING_BOOK = 'SET_EDITING_BOOK';
export const UNSET_EDITING_BOOK = 'UNSET_EDITING_BOOK';

export const SET_BOOKS = 'SET_BOOKS';
export const ADD_BOOK = 'ADD_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const DELETE_BOOK_BY_ID = 'DELETE_BOOK_BY_ID';
export const DELEFTE_FILE_BY_ID = 'DELETE_FILE_BY_ID';
export const UPDATE_FILE = 'UPDATE_FILE';

export const SET_FILES = 'SET_FILES';

export const SET_MIMES = 'SET_MIMES';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
